version: "3.9"

services:
  drive:
    build:
      context: .
      dockerfile: Dockerfile
    image: journey
    ports:
      - 8080:8080
    environment:
      - LISTEN_ADDRESS=:8080
    profiles:
      - core
