name: goreleaser

on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - '*'

env:
  # REGISTRY: docker.io
  # IMAGE_NAME: andrewprice/journey
  REGISTRY: images.linecas.com
  IMAGE_NAME: journey/journey

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
       name: Docker Login
       if: github.event_name != 'pull_request'
       uses: docker/login-action@v2
       with:
         registry: ${{ env.REGISTRY }}
         # username: ${{ secrets.DOCKER_HUB_USERNAME }}
         # password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
         username: ${{ secrets.NEXUS_USERNAME }}
         password: ${{ secrets.NEXUS_PASSWORD }}
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4.2.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      -
        name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Clear
        if: always()
        run: rm -f ${HOME}/.docker/config.json
