name: goreleaser

on:
  pull_request:
  push:
    branches:
    - main
    - pluralsight
    tags:
    - '*'

env:
  # REGISTRY: docker.io
  # IMAGE_NAME: andrewprice/journey
  REGISTRY: images.linecas.com
  IMAGE_NAME: journey/journey

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
       name: Docker Login
       uses: docker/login-action@v1
       with:
         registry: ${{ env.REGISTRY }}
         # username: ${{ secrets.DOCKER_HUB_USERNAME }}
         # password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
         username: ${{ secrets.NEXUS_USERNAME }}
         password: ${{ secrets.NEXUS_PASSWORD }}
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      -
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Clear
        if: always()
        run: rm -f ${HOME}/.docker/config.json
